#+title: Operating Principles of My Life
#+author: Parag Majumdar
#+DATE: <2023-06-16 Fri>
#+Time-stamp: <2023-06-16 Fri>
#+SETUPFILE: ../../../.setup/macros
#+SETUPFILE: ../../../.setup/options
#+OPTIONS: broken-links:mark H:2 title:t
#+STARTUP: fninline

#+begin_metadata
Published on {{{date(%e %b %Y)}}}
#+end_metadata

#+begin_share
{{{tweet(https://bitsofparag.com/blog/2023/06/operating-principles-of-my-life.html, Operating Principles of My Life)}}}
#+end_share

* Objective :noexport:

To share what I believe are the core principles of my life.

* Message :noexport:

TO inspire and stimulate. To provoke thoughts and encourage analysis. Readers should be able to understand what defines, describes and characterizes me as an individual. And hopefully, it also inspires them; enlightens them. Or encourages them to analyze the principles, questioning their validity or applicability. The goal is NOT to preach or advise.

* Tone :noexport:

  Thought-provoking / Inspiring / Pensive

* Intended audience :noexport:

#+begin_info

#+end_info

* {{{blog_intro(Standing in front of the black\, glossy stele now famously known as the Law of Hammurabi\,)}}}
I read its description online and one of its famous principles called "Lex Talionis" caught my attention. It is essentially the Law of Retaliation, taking "an eye for an eye, a tooth for a tooth", or in other words, the punishment for a crime should be proportional to the harm caused by the offender. This seems harsh or outdated by modern standards but it gives you a small insight into the moral values of the time. Would I accept the idea of hurting someone or be vengeful if I was wronged? Or would I take a few deep breaths and with a sane mind argue the case or even forgive and forget?

I left the museum towards home but found myself at this "moral crossroad", if you will; how would I inscribe my "Lex Talionis"? After some introspection, I jotted down a list of principles that I believe I operate on on a daily basis. They are not perfect, they likely have flaws but they direct my actions, help me navigate ups and downs in life, and define who I am as an individual. And they, certainly, can change with age and new learnings.

Following are the operating principles of my life. I am neither elaborating on them nor intending to offer advice or practical tips to the reader but I will be glad to discuss them.

- Life is about searching, yearning, longing and wanting. But take a few moments to be grateful for what you have.
- Practice empathy and understanding. They are two sides of the same coin. Both are key to forming strong, supportive relationships with others.
- Nature's diverse tapestry fosters balance and beauty. Appreciate and take care of its every creation, including us.
- Human first. A human-centric approach fosters fairness and equality. Only when necessary, consider factors such as ethnicity, religion, gender, or other categories to differentiate individuals.
- Eat healthy, exercise regularly and keep a healthy social life.
- Travel more. See more of the world. It enriches you culturally and broadens your perspective.
- Honesty leads to truthfulness; which leads to trustfulness; which makes one authentic and attractive. Be honest always.
- Altruism is good but hard. So, try to to give more than you wish to receive.
- If it hurts, don't experience it again. If it doesn't, it is worth a try.
- Life should be a healthy proportion of happiness to suffering. Mathematically speaking, keep that proportion greater than 1.
- Sometimes we experience loss to realize how to value and respect others before putting ourselves first. So, take every loss as a lesson to become a better version of yourself.
- Don't work in any establishment where the management doesn't understand the value its employees bring to its success.
- Take care of your team and lead by example. Be a leader, not a boss.
- Mistakes are gifts. Celebrate failures like you do on success.
- We are but bundles of energy gathering memories and stories as we journey through life in this ever-expanding universe. So, collect good memories and tell good stories.
- Always keep learning. But also un-learning. In other words, keep improving. Time spent on Earth doesn't mean you grow in mind.

So, what's my personal "Lex Talionis"? Well, the wrongdoer will not be a part of my healthy social life, so I would sever ties with them and put them out of my mind. And I would defer to the law for their rightful handling, if it comes to that.

* Discuss
{{{isso(https://pub.bitsofparag.com/comments)}}}
