#+title: Breaking Bread
#+author: Parag M.
#+date: <2020-05-24 Sun>
#+SETUPFILE: ~/.emacs.d/private/local/org-templates/org-base.setup
#+SETUPFILE: ~/.emacs.d/private/local/org-templates/level-2.org
#+OPTIONS: toc:nil broken-links:mark
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

* COMMENT Template

  #+begin_example
    Temp 23 °C and humidity 55%.

    ,*Ingredients*

    White flour - [[https://www.wurzener.de/produktwelt/kuchenmehl-type-550/][Wuzener 550]].

    Whole wheat - [[https://shop.rewe.de/p/rewe-bio-weizen-vollkornmehl-1kg/3100598][Rewe Bio]].

    Spelt flour - [[https://shop.rewe.de/p/rewe-bio-dinkel-vollkornmehl-1kg/3100603][Rewe Bio]].

    Mix of table salt and black kosher salt.

    ,#+TBLNAME: bread_items
    | Item        |  Qt |     % |
    |-------------+-----+-------|
    | Starter     |0    | 33.33 |
    | White flour | 0  | 46.67 |
    | Whole wheat |  0 | 26.67 |
    | Spelt flour |  0 | 26.67 |
    | Yeast       |   0 |  0.00 |
    | Salt        |   0 |  3.00 |
    | Water       | 0 | 68.33 |
    | Veggies     |   0 |  0.00 |
    |             |     |  0.00 |
    ,#+TBLFM: $3=($2 * 100)/(@3$2 + @4$2 + @5$2);%.2f

    ,#+TBLNAME: bread_process
    |  Time | Requirements               | State/Results              |
    |-------+----------------------------------------+----------------------------|
    | 00:00 |                                        |      |
    | 00:00 | White flour, Whole wheat, Spelt, water | [[#Actions][Autolyse]]. Rest.             |
    | 00:00 | Starter, salt                          |             |
    |   ... | Set a timer for every 20-25min                  | Stretch and fold.          |
    | 12:30 |                                                 | Cut.                       |

    ,** Verdict

    {{{img(/static/images/breaking-bread/25052020-bread-top.jpg, height:300px;)}}}

    - *Dough:*
      Some comment about dough.
    - *Baking:*
    - *Taste and texture:*
    - *Presentation:*

    [[#ToC][Back to contents]]
  #+end_example


  The pandemic crisis has made me breaking bread; by blending flour and water)
  that grows right before your eyes into a fluffy, sometimes stuffy, magical
  loaf.

* Contents
  :PROPERTIES:
  :CUSTOM_ID: ToC
  :END:
  - [[#References][References]]
  - [[#Actions][Actions]]
  - [[#Mixed W-L ST-S][Mixed W-L ST-S]]
  - [[#Overnight Proof Mixed W-S ST-M][Overnight Proof Mixed W-S ST-M]]
  - [[#Overnight Proof White W-S ST-M][Overnight Proof White W-S ST-M]]
  - [[#Overnight Proof W-Mixed W-M ST-M][Overnight Proof W-Mixed W-M ST-M]]
  - [[#Overnight Mixed W-M ST-S][Overnight Mixed W-M ST-S]]
  - [[#Day Bake White W-S ST-L][Day Bake White W-S ST-L]]
  - [[#Levain W-Mixed W-M ST-M][Levain W-Mixed W-M ST-M]]


* References
  :PROPERTIES:
  :CUSTOM_ID: References
  :END:
** Starter
   - ST-S : starter small, <20%
   - ST-M : starter medium, [20%, 35%)
   - ST-L : starter large, [35%, 50%]

** Water
   - W-S : water small, [55%, 65%)
   - W-M : water medium, [65%, 80%)
   - W-L : water large, [80%, 110%]

** Flour
   - White : all white bread flour with a little bit of whole wheat from the starter.
   - W-Mixed : mostly white flour mixed with smaller amounts of other types
     of flour.
   - Mixed : mix of white, wheat, spelt flours in nearly equal proportions.
   - R-Mixed : mostly rye flour mixed with other flours.
   - Rye : all rye flour, baby!

** Actions (in order of appearance in baking)
   :PROPERTIES:
   :CUSTOM_ID: Actions
   :END:
   - *Activate cold starter*
     By this I mean to wake up the yeast after having been kept in the
     refrigerator for sometime. I do this by keeping it on the kitchen bench to
     let it reach room temperature. You might start seeing little bubbles which
     means it is ready to be fed or levain-ed.

   - *Feed starter / Feed starter in ice*
   - *Float test* - Once the starter is active, you can take a small spoonful of
     it and place it gently in a container full of water. If it floats, it will
     bake! If it doesn't, check the interwebs for an answer :(
   - *Autolyse* - Autolysis is like suicide in the microscopic world. No
     really, that was my first reaction when I [[https://en.wikipedia.org/wiki/Autolysis_(biology)][read about it]]. But technically,
     it is a chemical reaction that happens when flour and water are mixed to
     break down the nutrients in wheat (or the grass you're using for the flour) into simple
     sugars and protein (which makes up the gluten). If you think about it,
     this step in bread-making, basically, partially digests the wheat grain for
     you so that your stomach can digest the rest of it. Feel free to experiment
     with the duration of autolyses with the type of grain and see what suits
     you. There's no exact science here in my opinion.
   - *Rest* - let the dough rest in the mixing bowl.
   - *Mix and light knead*
   - *Rubaud knead (optional)*
     There are many videos explaining this technique of kneading but the one
     that I liked is [[https://youtu.be/zgz0oAhgwyg?t=45][this one]].
   - *Stretch and fold / Slap and fold*
   - *Bulk rise*
   - *Pre-shape*
   - *Bench rest*
   - *Final shape*
   - *Proof in room / Proof in fridge*
   - *Pre-heat oven*
   - *Bake / Bake with steam* -
     Ideally, you would bake in a [[https://en.wikipedia.org/wiki/Dutch_oven][dutch oven]]. But since I couldn't move my fine
     ass to buy one (and I am hoping that I will get one as a present), what I do is fill a
     baking tray with ice or hot water and place it below the the tray where the
     bread is kept. The idea is to mimic the dutch oven to obtain a good oven-spring.
   - *Cool*
   - *Cut*

* Mixed W-L ST-S
  :PROPERTIES:
  :CUSTOM_ID: Mixed W-L ST-S
  :END:

Fed Starter.

Temp 23 °C and humidity 55%.

*Ingredients*

Starter - activated

Spelt flour - [[https://shop.rewe.de/p/rewe-bio-dinkel-vollkornmehl-1kg/3100603][Rewe Bio]].

Whole wheat - [[https://shop.rewe.de/p/rewe-bio-weizen-vollkornmehl-1kg/3100598][Rewe Bio]].

Rye flour - [[https://www.navoco.de/bauckhof-lichtkorn-roggenmehl-vollkorn-demeter-1000g][Demeter]].

Table salt

#+TBLNAME: bread_items
| Item                               |  Qt |     % |
|------------------------------------+-----+-------|
| Starter                            |  80 | 17.98 |
| Spelt flour                        | 263 | 59.10 |
| Whole wheat                        | 173 | 38.88 |
| Rye flour                          |  43 |  9.66 |
| Salt                               |   9 |  2.02 |
| Water                              | 362 | 81.35 |
| Seasoning - poppy, garlic, linseed |     |        |                                    |     |       |
#+TBLFM: $3=($2 * 100)/(@3$2 + @4$2 + @6$2);%.2f

#+TBLNAME: bread_process
|  Time | Requirements                               | State/Results              |
|-------+--------------------------------------------+----------------------------|
| 16:00 | Water, Spelt flour, Whole wheat, Rye flour | [[#Actions][Autolyse]]. Rest.            |
| 16:30 | Salt, starter                              | Mix and light knead. Rest. |
| 17:00 | Seasoning                                  | Stretch and fold.          |
| 17:30 |                                            | Stretch and fold.          |
|   ... | Set a timer for every 30min                | Stretch and fold.          |
| 21:00 |                                            | Bulk rise in room          |
| 06:50 |                                            | Final shape.               |
| 07:00 |                                            | Proof.                     |
|       |                                            |                            |

** Verdict

{{{img(/static/images/breaking-bread/25052020-bread-top.jpg, height:300px;)}}}

- *Dough:*
  Some comment about dough.
- *Baking:*
- *Taste and texture:*
- *Presentation:*

[[#ToC][Back to contents]]


* Overnight Proof Mixed W-S ST-M
  :PROPERTIES:
  :CUSTOM_ID: Overnight Proof Mixed W-S ST-M
  :END:


Temp 24.8 °C and humidity 45-50% in the kitchen.

** Recipe

White flour - [[https://www.wurzener.de/produktwelt/kuchenmehl-type-550/][Wuzener 550]].

Whole wheat - [[https://shop.rewe.de/p/rewe-bio-weizen-vollkornmehl-1kg/3100598][Rewe Bio]].

Spelt flour - [[https://shop.rewe.de/p/rewe-bio-dinkel-vollkornmehl-1kg/3100603][Rewe Bio]].

Mix of table salt and black kosher salt.

#+TBLNAME: bread_items
| Item        |  Qt |     % |
|-------------+-----+-------|
| Starter     | 107 | 23.78 |
| White flour | 200 | 44.44 |
| Whole wheat | 150 | 33.33 |
| Spelt flour | 100 | 22.22 |
| Water       | 265 | 58.89 |
| Salt        |   8 |  1.78 |
#+TBLFM: $3=($2 * 100)/(@3$2 + @4$2 + @5$2);%.2f

#+TBLNAME: bread_process
|  Time | Requirements                                    | State/Results              |
|-------+-------------------------------------------------+----------------------------|
| 11:30 |                                                 | Feed starter.              |
| 16:00 | White flour, Whole wheat, Spelt, Starter, water | Autolyse. Rest.            |
| 16:40 | Salt                                            | Mix and light knead. Rest. |
| 17:00 |                                                 | Stretch and fold.          |
| 17:20 |                                                 | Stretch and fold.          |
|   ... | Set a timer for every 20-25min                  | Stretch and fold.          |
| 19:30 |                                                 | Stretch and fold.          |
| 19:30 |                                                 | Bulk rise.                 |
| 23:00 |                                                 | Pre-shape. Bench rest.     |
| 00:00 |                                                 | Final shape.               |
| 00:05 |                                                 | Proof in fridge.           |
| 08:15 |                                                 | Pre-heat oven.             |
| 08:45 |                                                 | Bake.                      |
| 09:45 |                                                 | Cool.                      |
| 12:30 |                                                 | Cut.                       |

** Verdict

{{{img(/static/images/breaking-bread/30052020-final-shape.jpg, width:300px;)}}}
{{{img(/static/images/breaking-bread/30052020-bread-top.jpg, width:400px;)}}}
{{{img(/static/images/breaking-bread/30052020-bread-side.jpg, width:350px;)}}}
{{{img(/static/images/breaking-bread/30052020-slices.jpg, width:350px;)}}}

- *Dough:*
  Beautiful dough; a pleasure to work with. Felt very light and airy,
  especially during final shaping. I wish our brains were like this. I had the
  briefest idea of making a parachute out of it but I let it pass and
  moved on to proofing this amazing dough in the fridge.

- *Baking:*
  The fermented dough looked good - poke test passed with flying colors. I
  decided to place a wet kitchen towel instead of ice or boiling water to
  facilitate a more prolonged steaming process. Turned out to be a terrible
  idea. Not only did the towel start to char as it dried, the smell of the cloth
  itself mixed with the steam. Stupid, stupid!

- *Taste and texture:*
  I thought the kitchen towel debacle would ruin the bread from the inside (the
  smell was a teeny-bit off but nowhere close to bad). But
  no, it tasted awesome. The burnt flax and the chia seeds gave it a new smell
  and taste - can't say I liked it enormously over the others.
  A tad low on salt (1.78% as per the table) - maybe I
  should hit the 2% mark for good flavor. Not stuffy. Air pockets are uniformly
  distributed. Feels soft and light. Slight tangy smell.

- *Presentation:*
  I am still out of luck here. I had slashed the bread like Zorro.
  The rise was fine. But no oven-spring, the brazen scoring failed to facilitate
  that. Maybe I am missing something. Can't figure out what it is.

[[#ToC][Back to contents]]

* Overnight Proof White W-S ST-M
  :PROPERTIES:
  :CUSTOM_ID: Overnight Proof White W-S ST-M
  :END:

Temp 23 °C and humidity 55%.

** Recipe

 White flour - [[https://www.wurzener.de/produktwelt/kuchenmehl-type-550/][Wuzener 550]].

 Mix of table salt and black kosher salt.

 #+TBLNAME: bread_items
 | Item         | grams |      % |
 |--------------+-------+--------|
 | Starter      |    80 |  24.39 |
 | White flour  |   328 | 100.00 |
 | Salt         |     9 |   2.74 |
 | Water        |   197 |  60.06 |
 | Olive oil    |     3 |   0.91 |
 | Sesame seeds |     3 |   0.91 |
 #+TBLFM: $3=($2 * 100)/(@3$2 + @4$2 + @5$2);%.2f

 #+TBLNAME: bread_process
 |  Time | Requirements                           | State/Results                 |
 |-------+----------------------------------------+-------------------------------|
 | 10:00 | Warm oven from last bake               | Activate cold starter.        |
 | 13:00 | White flour, water                     | Autolyse. Rest.               |
 | 14:00 | Starter, sesame seeds, olive oil, salt | Mix and light knead. Rest.    |
 | 14:30 |                                        | Stretch and fold.             |
 |   ... | Set a timer for every 20-30min         | Stretch and fold.             |
 | 17:00 |                                        | Stretch and fold.             |
 | 17:30 |                                        | Pre-shape. Bench rest.        |
 | 18:30 |                                        | Final shape. Proof in fridge. |
 | 08:00 |                                        | Pre-heat oven.                |
 | 08:30 |                                        | Bake.                         |
 | 09:40 |                                        | Cool.                         |
 | 11:00 |                                        | Cut.                          |

** Verdict

{{{img(/static/images/breaking-bread/25052020-bread-top.png, height:300px;)}}}
{{{img(/static/images/breaking-bread/25052020-slices.jpg, height:400px;)}}}

Compared to the bread from [[#Overnight Proof W-Mixed W-M ST-M][the last bake]]:

{{{img(/static/images/breaking-bread/25052020-slices-2.jpg, width:400px;)}}}

- *Dough:* Clearly, the gluten structure was strong because of higher than usual proportion of white flour.
  However, my manly hands broke the structure after adding the starter and salt - /I should
  be careful with the kneading/. What was lost in brute force was gained in
  patience and technique later on with many rounds of stretch and fold. The
  gluten was mostly restored but I didn't have a great feeling about it. And
  that ruined my plan to do fewer stretch and folds than last time, as I had noted.

- *Baking* After pre-heating at 250°C, I set the final dough over a tray of boiling water
  for about 20 min. The browning was good. The oven-spring seemed to look good
  as well. I am not gonna lie, I sat next to the oven to watch it grow in front
  of my eyes. The scariest part was when the dough stayed flat for a good 15min
  and I started to wonder if I unknowingly killed millions of yeast during
  proofing in the fridge. But around the 20 minute mark, /*poof*/, lo and
  behold, the dough rose like dead angels!

- *Taste and texture* Definitely in the top three of what I've made so far (/which would be six/),
  in terms of taste. The texture, hmmm, not so sure. The crumb wasn't very open.
  With almost complete white flour and around 60-65% hydration, I expected a better
  crumb. /Should experiment with lower water for white flour next time./ Or
  higher water with whole wheat. Anyways, the stiffness of the bread is
  dependent on many variables, the brand of white flour being one of them. So,
  gotta be patient and keep baking and learn from trials and errors.

- *Presentation* I was confident that the scoring would work this time. It looked very
  promising through the hazy oven window as I watched the rise of the dough
  (/Heh, "Rise of the Dough" could be a sequel to "The Dough".)/ But, from the
  picture you can see what happened. The yeasty gases didn't push out; hence, no
  oven-spring or an open crumb. /I should be more ambitious with the scoring next time./

[[#ToC][Back to contents]]

* Overnight Proof W-Mixed W-M ST-M
  :PROPERTIES:
  :CUSTOM_ID: Overnight Proof W-Mixed W-M ST-M
  :END:

  Temp 23 °C and humidity 55%.

** Recipe

  White flour - [[https://www.wurzener.de/produktwelt/kuchenmehl-type-550/][Wuzener 550]].

  Whole wheat - [[https://shop.rewe.de/p/rewe-bio-weizen-vollkornmehl-1kg/3100598][Rewe Bio]].

  Spelt flour - [[https://shop.rewe.de/p/rewe-bio-dinkel-vollkornmehl-1kg/3100603][Rewe Bio]].

  Charcoal kosher salt.

  #+TBLNAME: bread_items
  | Item        |  Qt |     % |
  |-------------+-----+-------|
  | Starter     | 100 | 33.33 |
  | White flour | 140 | 46.67 |
  | Whole wheat |  80 | 26.67 |
  | Spelt flour |  80 | 26.67 |
  | Salt        |   9 |  3.00 |
  | Water       | 205 | 68.33 |
  #+TBLFM: $3=($2 * 100)/(@3$2 + @4$2 + @5$2);%.2f


  #+TBLNAME: bread_process
  |  Time | Ingredients                            | State/Results              |
  |-------+----------------------------------------+----------------------------|
  | 11:00 |                                        | Activate cold starter.     |
  | 15:00 | White flour, Whole wheat, Spelt, water | [[#Actions][Autolyse]]. Rest             |
  | 15:30 | Starter, salt, soaked chia seeds       | Mix and light knead. Rest. |
  | 16:05 |                                        | [[#Actions][Rubaud knead]].              |
  | 16:30 |                                        | Rubaud knead.              |
  | 16:50 |                                        | Rubaud knead.              |
  | 17:15 |                                        | Rubaud knead.              |
  | 18:00 |                                        | Stretch and fold.          |
  |   ... | Set a timer for every 20-30min         | Stretch and fold.          |
  | 21:00 |                                        | Stretch and fold.          |
  | 21:30 |                                        | Pre-shape.                 |
  | 22:00 |                                        | Final shape.               |
  | 22:05 |                                        | Proof in fridge.           |
  | 06:30 |                                        | Pre-heat oven.             |
  | 07:00 |                                        | Bake.                      |
  | 07:50 |                                        | Cool.                      |
  | 09:00 |                                        | Cut.                       |

** Verdict

  {{{img(/static/images/breaking-bread/24052020-cross-section.jpg, height:500px;)}}}
  {{{img(/static/images/breaking-bread/24052020-slices.jpg, height:400px;)}}}
  {{{img(/static/images/breaking-bread/24052020-bread-score.jpg, height:418px;)}}}

  - *Dough:* Soft and wet dough. Super easy to knead, stretch and fold. The
    soaked chia seeds probably increased the hydration beyond 70%. The
  Rubaud knead technique helped soak all the water up. Though it seemed that it
  got wetter through the stretch and folds, not sure why. I will admit that I
  love this part of the bread-making process - working the dough and then
  shaping it, is like being a good father doting on his baby while changing the
  diaper. *Does that mean I'm ready?* To bake more bread?

  - *Baking:* Baked at 250°C for the most part. I placed a tray full of boiling water to
  mimic the dutch oven.

  - *Taste and texture:* Was very delicious. With salt content at 3%, the flavor is hard to miss.
  /Could it be because I used a fancy black-colored kosher salt?/ The
  crumb is soft, airy. Not so stiff.

  - *Presentation:* Nope. Nada. The bread scoring looked professional, if you ask me. But it
  hardly allowed the bread to open up. Looked like a scar on a mob boss' face
  /(see first photo above)/. The dark color of the bread was prominent due to
  the addition of the salt.

[[#ToC][Back to contents]]

* Overnight Mixed W-M ST-S
  :PROPERTIES:
  :CUSTOM_ID: Overnight Mixed W-M ST-S
  :END:

  Temp 22.1 °C and humidity 53%.

** Recipe

  White flour - [[https://www.kathi.de/weizenmehl-type-405/][Kathi 405]].

  Whole wheat - [[https://shop.rewe.de/p/rewe-bio-weizen-vollkornmehl-1kg/3100598][Rewe Bio]].

  Table salt.

  #+TBLNAME: bread_items
  | Item        |  Qt |     % |
  |-------------+-----+-------|
  | Starter     |  90 | 19.96 |
  | White flour | 301 | 66.74 |
  | Whole wheat | 150 | 33.26 |
  | Salt        |  10 |  2.22 |
  | Water       | 349 | 77.38 |
  #+TBLFM: $3=($2 * 100)/(@3$2 + @4$2);%.2f


  #+TBLNAME: bread_process
  |  Time | Ingredients                     | State/Results                 |
  |-------+---------------------------------+-------------------------------|
  | 18:32 | white flour, whole wheat, water | Autolyse. Rest.               |
  | 19:10 | Starter, salt                   | Mix and fold. Rest.           |
  | 19:30 |                                 | Stretch and fold.             |
  | 19:45 |                                 | Stretch and fold.             |
  | 20:00 |                                 | Stretch and fold.             |
  | 20:30 |                                 | Shape. Cover and rest.        |
  | 06:40 |                                 | Divide. Pre-shape.            |
  | 06:58 |                                 | Final shape. Proof in fridge. |
  | 16:50 |                                 | Bake.                         |
  | 17:35 |                                 | Cool.                         |
  | 20:00 |                                 | Cut.                          |

** Verdict

   {{{img(/static/images/breaking-bread/15052020-slices.jpg, width:350px;)}}}
   {{{img(/static/images/breaking-bread/15052020-slices-2.jpg, width:350px;)}}}
   {{{img(/static/images/breaking-bread/15052020-bread-side.jpg, width:350px;)}}}
   {{{img(/static/images/breaking-bread/15052020-final-shape.jpg, width:350px;)}}}

   Having me some delicious bread with delicious spread:
   {{{img(/static/images/breaking-bread/16052020-slices.jpg, width:500px;)}}}

   - *Dough* The experience from the [[#Levain W-Mixed W-M ST-M][previous, high-hydration bread]] was enough to
     encourage me to learn how to shape such a dough - check out [[https://www.youtube.com/watch?v=vEG1BjWroT0][this video]] to
     get a good idea on how to do so. *So, how did I do?* So bad that I wanted
     to kill myself. Anyways, I somehow managed to rein in the sticky dough and
     took a big sigh of relief after plopping it into the proofing bowl.

  - *Baking* Funny thing happened, the base of the final dough wouldn't let go
    of the proofing bowl when I turned it upside-down to place it on the kitchen
    bench. The flip stretched the dough to it limits, I shrieked and quickly
    moved in with my hands to finish the transfer. My heart pounded like a race
    car. Luckily for me, the kitchen bench offered another opportunity to shape
    the dough before placing it on the baking tray.

   - *Taste and texture*
     Tasted good. Well salted. Smell, sour and fresh. From the pics you can
     clearly see big, gaping holes, especially at the top of the bread. That
     must be the loosening of the dough at the top edge due to the botched-up
     transfer. There were some big holes in the middle as well, *as if a
     super-yeast punched through the dough and escaped the hellish death of the
     oven furnace!*

   - *Presentation*
     *This was my first attempt at scoring with a small paring knife.* If you
     would call it scoring, really! I felt bad to leave a small, pointless cut
     in an otherwise nice looking dough. Better luck next time. Also, the final
     bread looked like a blob of mud - I wouldn't last long as a baker with that
     kind of output.

* Day Bake White W-S ST-L
  :PROPERTIES:
  :CUSTOM_ID: Day Bake White W-S ST-L
  :END:

Temp 21.7 °C and humidity 44%.

** Recipe

White flour - [[https://www.kathi.de/weizenmehl-type-405/][Kathi 405]].

Table salt.

#+TBLNAME: bread_items
| Item         |  Qt |      % |
|--------------+-----+--------|
| Starter      | 114 |  37.87 |
| White flour  | 301 | 100.00 |
| Yeast        |   7 |   2.33 |
| Salt         |   9 |   2.99 |
| Water        | 170 |  56.48 |
| Sesame seeds |     |        |
#+TBLFM: $3=($2 * 100)/(@3$2 + @4$2);%.2f


#+TBLNAME: bread_process
|  Time | Requirements                       | State/Results               |
|-------+------------------------------------+-----------------------------|
| 09:00 | Starter, white flour, yeast, water | Mix and knead. Rest.        |
| 09:23 | Salt                               | Mix and knead. Rest.        |
| 09:30 |                                    | Bulk rise.                  |
| 13:20 |                                    | Pre-shape. Rest.            |
| 15:00 | Sesame seeds                       | Final shape. Pre-heat oven. |
| 15:24 |                                    | Bake with ice.              |
| 16:00 |                                    | Cool.                       |
| 17:30 |                                    | Cut.                        |

** Verdict

   {{{img(/static/images/breaking-bread/11052020-bread-top.jpg, width:300px;)}}}
   {{{img(/static/images/breaking-bread/11052020-slices.jpg, width:450px;)}}}

  - *Dough*
    This was the first attempt at combining starter yeast and industrial instant
    yeast. So, I didn't perform any stretch and folds, just let it bulk rise to
    double the size. Not bad if you have a busy day. It was easier to manage
    than the last time which was a disaster.

  - *Baking*
    This was a low temperature bake, kept the oven at 200°C. I placed a tray of
    ice at the bottom, below the bread-tray. The idea is to sweat the ice to
    provide some steam to the dough as it rises. Apparently, this mimics the
    dutch oven. /I wonder who first came up with this idea for novice sourdough
    bakers like me?/

  - *Taste*
    Tasted amazing - the mild sourness with saltiness, close to 3% salt.
    However, with about 40% starter, I expected it to be more tangy. Either my
    taste buds were sleeping or a high starter content does not directly
    correlate to higher tanginess. /Why, oh natural world, why? Why do you bereft
    me of amazing sour bread flavor!/ Also, there was more salt near the crust
    than the inside. Some stretch and folds would have definitely helped.

  - *Texture*
    The crumb was a bit stiff. Not many pockets of air. Maybe the lack of
    stretch and fold caused that. Or the mixing of different types of yeast.
    Something to experiment with on the next bake.

  - *Presentation*
    A sprinkle of seeds on top goes a long way in enhancing the presentation.
    I haven't started scoring the dough yet. *I should do it the next time as it
    might bring the texture within expectations, besides making it look like the
    Youtube-couture sourdough breads.* I liked the light golden brown
    color, since I didn't bake above 200. There is a linear gash on one side of
    the bread, where the gases might have burst out. /Better score the dough
    next time./

 [[#ToC][Back to contents]]

* Levain W-Mixed W-M ST-M
  :PROPERTIES:
  :CUSTOM_ID: Levain W-Mixed W-M ST-M
  :END:

Temp 22 °C and humidity 50%.

** Recipe

   White flour - [[https://www.wurzener.de/produktwelt/kuchenmehl-type-550/][Wuzener 550]].

   Whole wheat - [[https://shop.rewe.de/p/rewe-bio-weizen-vollkornmehl-1kg/3100598][Rewe Bio]].

   Spelt flour - [[https://shop.rewe.de/p/rewe-bio-dinkel-vollkornmehl-1kg/3100603][Rewe Bio]].

   Table salt.

   #+TBLNAME: bread_items
   | Item        |  Qt |     % |
   |-------------+-----+-------|
   | Starter     | 114 | 32.48 |
   | White flour | 251 | 71.51 |
   | Whole wheat |  50 | 14.25 |
   | Spelt flour |  50 | 14.25 |
   | Salt        |  10 |  2.85 |
   | Water       | 260 | 74.07 |
   #+TBLFM: $3=($2 * 100)/(@3$2 + @4$2 + @5$2);%.2f


   #+TBLNAME: bread_process
   |  Time | Ingredients                                          | State/Results              |
   |-------+------------------------------------------------------+----------------------------|
   | 18:00 |                                                      | Activate cold starter.     |
   | 23:30 | Starter (17g), water (93g), White (46g), Wheat (46g) | Make levain.               |
   | 08:45 |                                                      | Float test pass/fail.      |
   | 08:45 | White flour, Whole wheat, Spelt flour, water, levain | Mix and light knead. Rest. |
   | 09:14 | Salt, water (15g)                                    | Mix and light knead. Rest. |
   | 09:15 |                                                      | Stretch and fold.          |
   |   ... | Set a timer for every 30-35min                       | Stretch and fold.          |
   | 14:25 |                                                      | Stretch and fold.          |
   | 14:45 |                                                      | Pre-shape.                 |
   | 15:45 |                                                      | Final shape.               |
   | 15:50 |                                                      | Proof.                     |
   | 21:00 |                                                      | Pre-heat oven.             |
   | 21:30 |                                                      | Bake                       |
   | 22:10 |                                                      | Cool.                      |
   | 10:00 |                                                      | Cut.                       |

** Verdict

   So, this was my first, earnest attempt at baking a sourdough bread /(after
   days of reading and watching Youtube-bakers)/. Here are
   some pictures of how that turned out.

   {{{img(/static/images/breaking-bread/05052020-bread-top.jpg, width:350px;)}}}
   {{{img(/static/images/breaking-bread/05052020-slices.jpg, width:350px;)}}}
   {{{img(/static/images/breaking-bread/05052020-final-shape.jpg, width:350px;)}}}
   {{{img(/static/images/breaking-bread/05052020-levain.jpg, width:350px;)}}}

   - *Dough*
     Being the first time, I didn't really anticipate how the dough would behave
     with a hydration of over 75% /(and I poured in more water when I added the
     salt)/. Stretch and fold exercise was fun. I never knew the dough could be
     treated like that without kneading. But i found it quite challenging to
     pre-shape, sticking to the bench like glue. Eventually, I managed to give
     it a nice round shape /(see pics)/.

   - *Baking*
     Had to proof a long time (almost 5.5h) since the dough was taking time to be set.
     *Transfer from proofing case to the baking tray was a disaster*. The dough
     stuck really badly to the case and spread flat on the baking tray. Gotta be
     careful next time.
     *Baked at 230°C with boiling water added for steam for 30min. Then 200°C
     for 15min.*

   - *Taste and texture*
     Very, very nice, I'd say. I didn't have a restaurant sourdough bread to
     compare with but I really loved how it turned out. Not an open crumb like
     the Youtube-couture sourdough breads but satisfying to the eye and to the
     touch.

** Learnings
   - Maybe keep the levain in a warmer place - oven with the light on.
   - Be careful during transfer to baking tray.


 [[#ToC][Back to contents]]
